### ISSUE TITLE
Entity Properties Naming Conventions

### ISSUE THREAD

**Issue by OmerCD** [cnKyV/Lib#2]
No need to name identification field using Entity's name as prefıx. Examples :
`namespace LIB.Core.Entities
{
    public class Author
    {
        public int AuthorId { get; set; }
        public string Name { get; set; }
...`

Where `AuthorId` can simply be  `Id`

**Comment by cnKyV** [comment]
Entity name prefixes have been excluded, instead they are renamed to "Id" as it should've been, thanks for the heads up!
