### ISSUE TITLE
Possible Multiple Access To Database

### ISSUE THREAD

**Issue by OmerCD** [cnKyV/Lib#5]
Accessing database inside a loop is a bad practice and this referenced line is potentially doing that. For preventing really big performance issues, required access should only made once for all needed information than you should be able to use that.

https://github.com/cnKyV/Lib/blob/2af7ffb0cec5692179386a454db70bcd041a15ce/LIB.Domain/Requests/AuthorRequest.cs#L34

**Comment by cnKyV** [comment]
```
 var result = _bookService.GetMultipleByIds(author.Books);
           
            foreach (var ids in result)
            {
                var moq = new AuthorBook();
                moq.Book = ids;
                query.Books.Add(moq);
            }
```

BookRepository;

```
        public ICollection<Book> GetMultipleById(ICollection<int> ids)
        {
            return  _libDbContext.Books.Where(i => ids.Contains(i.Id)).Select(i=>i).ToList();
        }
```

Is this appropriate now?

**Comment by OmerCD** [comment]
> ```
>  var result = _bookService.GetMultipleByIds(author.Books);
>            
>             foreach (var ids in result)
>             {
>                 var moq = new AuthorBook();
>                 moq.Book = ids;
>                 query.Books.Add(moq);
>             }
> ```
> 
> BookRepository;
> 
> ```
>         public ICollection<Book> GetMultipleById(ICollection<int> ids)
>         {
>             return  _libDbContext.Books.Where(i => ids.Contains(i.Id)).Select(i=>i).ToList();
>         }
> ```
> 
> Is this appropriate now?

No need for `Select(i=>i)` statement. And `ICollection<int> ids` can be `IEnumerable<int> ids`.

**Comment by cnKyV** [comment]
@OmerCD What do you exactly mean by "can be"? Is there any specific reason why should I favor `IEnumerable<int>` over `ICollection<int>` in this specific situation.

**Comment by OmerCD** [comment]
> @OmerCD What do you exactly mean by "can be"? Is there any specific reason why should I favor `IEnumerable<int>` over `ICollection<int>` in this specific situation.

ICollection interface has bunch of unnecessary method (Like `Add()`) that you are not using in your method. So it is a better practice to use base type. You are only using `Contains()` method and IEnumerable is the most basic type that method can be used.
